name=eOS3
version=1.0.0
author=Stefan Staub
maintainer=Stefan Staub <stefan.staub@lichtkunst-kunstlicht.de.com>
sentence=ETC EOS library for OSC
paragraph=Arduino library to control ETC EOS consoles using OSC over USB and UDP/TCP.
category=Device Control
url=https://github.com/sstaub/eOS3
architectures=*
includes=eOS3.h
